### ISSUE TITLE
No ColorColumn support

### ISSUE THREAD

**Issue by mikeyT42** [zootedb0t/citruszest.nvim#23]
It seems as though there is no color column support in this theme. I set a width, which works in standard themes, and when applying this theme the color column is not shown.

Can this feature be added to this theme? Is there a configuration needed?

**Comment by zootedb0t** [comment]
There is already `ColorColumn` support in this theme. It is set to `none` that's why you don't see anything. [see](https://github.com/zootedb0t/citruszest.nvim/blob/60e6cec400cd857ffd69d582794c3ce5571c0049/lua/citruszest/highlights/init.lua#L8).

If you want to change `ColorColumn` highlight just override it.

**Comment by mikeyT42** [comment]
Thank you, that should do the trick.
